version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Required
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Security
    - gosec
    - noctx
    - bodyclose
    - sqlclosecheck
    # Error handling
    - errorlint
    - errchkjson
    - wastedassign
    # Best practices
    - gocritic
    - revive
    - unconvert
    - dupl
    - goconst
    - misspell
    - prealloc
    - copyloopvar

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - govet

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
